project:
  output-dir: docs
  type: website
  pre-render: ./_includes/_pre-render.sh
  render:
    - index.qmd
    - day1-fundamentals.qmd
    - day2-advanced.qmd
    - further-reading.qmd
    - "!rv/"

execute:
  freeze: true

format:
  html:
    css: _includes/website.css

website:
  title: "IQB Workshop — Graphical Causal Inference"
  navbar:
    background: "#107895"
    left:
      - text: Day 1 — Fundamentals
        href: day1-fundamentals.qmd
      - text: Day 2 — Advanced
        href: day2-advanced.qmd
      - text: Further Reading
        href: further-reading.qmd
